### ISSUE TITLE
.htaccess problem

### ISSUE THREAD

**Issue by alexbagirov** [gautamkrishnar/Anchor-CMS-openshift-quickstart#2]
During the installation it told me that mod_rewrite is supported so `.htaccess` will be set automaticaly. Now my installation is finished and all links throw 404. 

How to fix it?

**Comment by gautamkrishnar** [comment]
@alexbagirov thanks for reporting. i will give it a check and will inform you about the fix. Just a minute...

**Comment by gautamkrishnar** [comment]
not fixed... working on it...

**Comment by alexbagirov** [comment]
@gautamkrishnar ok

**Comment by gautamkrishnar** [comment]
@alexbagirov for fixing this issue with your currently deployed app type the following commands after logging into app using ssh:

```
cd ${OPENSHIFT_REPO_DIR}/php/
wget https://raw.githubusercontent.com/gautamkrishnar/Anchor-CMS-openshift-quickstart/master/.openshift/config/.htaccess
```
